Repository ReliefApplications/ems-backend, pull requests merged in 2022-10, with the labels that each got.

#414 feat-1.4.0/AB#41412_building-derived-column-pipeline
  src/const/calculatedFields.ts
  src/schema/mutation/editResource.mutation.ts
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
  src/utils/aggregation/expressionFromString.ts
  src/utils/form/findDuplicateFields.ts
  src/utils/schema/resolvers/Query/all.ts
Labels: feature

#424 feat-1.4.0/AB#41414_date-operations
  __tests__/schema/query/applications.test.ts
  src/const/calculatedFields.ts
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
  src/utils/aggregation/expressionFromString.ts
  src/utils/form/findDuplicateFields.ts
  src/utils/form/transformRecord.ts
Labels: enhancement

#435 Feat 1.2.0/ab#35306 add limit in sort
  src/utils/query/queryBuilder.ts
  src/utils/schema/introspection/getSchema.ts
  src/utils/schema/resolvers/Entity/index.ts
Labels: enhancement

#434 fix-1.4.0/AB#41420_calculated_cols_for_styling
  src/const/calculatedFields.ts
  src/schema/mutation/editResource.mutation.ts
  src/utils/aggregation/expressionFromString.ts
  src/utils/schema/resolvers/Query/all.ts
Labels: bug, enhancement

#426 fix-1.4.0/AB#41413_concat-non-string-types
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
Labels: bug

#436 Feat 1.4.0/ab#41421 calculated fields on aggregations
  src/schema/query/recordsAggregation.query.ts
Labels: enhancement

#422 OORT-469 Fix authentication in tests - back-end
  .github/workflows/ci.yml
  __tests__/authentication.setup.ts
  __tests__/integration.test.ts
  __tests__/jest.setup.ts
  __tests__/server.setup.ts
  config/test.js
  docker-compose.test.yml
  package.json
  src/security/defineUserAbility.ts
Labels: bug, enhancement

#441 feat-1.2.1/AB#42577_email-templates-def
  TODO.md
  src/const/errors.ts
  src/const/permissions.ts
  src/models/application.ts
  src/models/index.ts
  src/models/template.ts
  src/schema/inputs/template.input.ts
  src/schema/mutation/addTemplate.ts
  src/schema/mutation/deleteTemplate.ts
  src/schema/mutation/editApplication.ts
  src/schema/mutation/editTemplate.ts
  src/schema/mutation/index.ts
  src/schema/types/application.ts
  src/schema/types/index.ts
  src/schema/types/template.ts
  src/security/defineAbilityFor.ts
  src/security/extendAbilityForApplication.ts
  src/server/database.ts
  src/setup/migrateTemplates.ts
Labels: enhancement

#442 fix-1.3.0/AB#35599_related-cols
  src/utils/schema/resolvers/Entity/index.ts
Labels: bug

#430 refactor-1.3.0/AB#42125 remove setting model + replace by config
  config/default.js
  src/i18n/en.json
  src/i18n/test.json
  src/models/index.ts
  src/models/setting.model.ts
  src/routes/permissions/index.ts
  src/schema/mutation/addGroup.mutation.ts
  src/schema/mutation/editSetting.mutation.ts
  src/schema/mutation/editUserProfile.mutation.ts
  src/schema/mutation/fetchGroups.mutation.ts
  src/schema/mutation/index.ts
  src/schema/query/index.ts
  src/schema/query/me.query.ts
  src/schema/types/index.ts
  src/schema/types/setting.type.ts
  src/security/defineUserAbility.ts
  src/server/database.ts
  src/server/fetchGroups.ts
  src/server/middlewares/auth.ts
  src/utils/auth/user-auth-callback.helper.ts
  src/utils/proxy/authManagement.ts
  src/utils/user/fetchGroups.ts
  src/utils/user/getAutoAssignedRoles.ts
  src/utils/user/index.ts
  src/utils/user/updateUserAttributes.ts
  src/utils/user/updateUserGroups.ts
  src/utils/user/userManagement.ts
Labels: enhancement, refactor

#443 fix-1.3.0/OORT-443_initDatabase-checks
  src/server/database.ts
Labels: bug
