Repository ReliefApplications/ems-backend, pull requests merged in 2022-12, with the labels that each got.

#456 Fix 1.3.0/AB#27480 history xls generation
  src/i18n/en.json
  src/i18n/test.json
  src/routes/download/index.ts
  src/schema/mutation/addApplication.mutation.ts
  src/schema/mutation/addRecord.mutation.ts
  src/schema/mutation/duplicateApplication.mutation.ts
  src/schema/mutation/editApplication.mutation.ts
  src/schema/mutation/editRecord.mutation.ts
  src/schema/mutation/editRecords.mutation.ts
  src/schema/mutation/editUserProfile.mutation.ts
  src/schema/mutation/seeNotification.mutation.ts
  src/schema/mutation/seeNotifications.mutation.ts
  src/schema/mutation/toggleApplicationLock.mutation.ts
  src/schema/types/application.type.ts
  src/security/defineUserAbility.ts
  src/server/pullJobScheduler.ts
  src/utils/date/getTimeWithTimezone.ts
  src/utils/files/fileBuilder.ts
  src/utils/files/historyBuilder.ts
  src/utils/form/getDisplayText.ts
  src/utils/history/recordHistory.ts
  src/utils/user/updateUserAttributes.ts
  src/utils/user/updateUserGroups.ts
  src/utils/user/userManagement.ts
Labels: bug, enhancement

#455 Feat 1.4.0/ab#42921 custom notification sort filter the table
  src/const/enumTypes.ts
  src/models/customNotification.model.ts
  src/schema/mutation/addCustomNotification.mutation.ts
  src/schema/types/application.type.ts
Labels: enhancement

#459 Feat 1.4.0/ab#42923 custom notification use email template
  src/server/customNotificationScheduler.ts
Labels: enhancement

#463 AB#50994 fix issue with .equals on undefined
  src/security/extendAbilityForRecords.ts
Labels: bug, released

#465 Fix 1.3.0/AB#51124 history generation date field
  src/schema/mutation/addRecord.mutation.ts
  src/schema/mutation/editRecord.mutation.ts
  src/schema/mutation/editRecords.mutation.ts
  src/server/pullJobScheduler.ts
  src/utils/form/transformRecord.ts
  src/utils/history/recordHistory.ts
Labels: bug, enhancement

#473 fix/OORT-531_linked-fileds-as-coords
  src/utils/form/metadata.helper.ts
  src/utils/schema/resolvers/Query/getFilter.ts
Labels: enhancement

#480 Fix 1.3.x/ab#51909 Avoid surveyJS validation error
  package-lock.json
  package.json
  src/schema/mutation/editRecord.mutation.ts
  src/server/index.ts
  src/services/form.service.ts
  src/utils/form/extractFields.ts
  src/utils/form/metadata.helper.ts
  src/utils/form/transformRecord.ts
  test.json
  tsconfig.json
Labels: bug, help wanted
