Repository ReliefApplications/ems-backend, pull requests merged in 2022-11, with the labels that each got.

#444 feat-1.3.0/OORT-491_attr-in-permission-module
  src/schema/query/form.query.ts
  src/utils/schema/resolvers/Query/getFilter.ts
  src/utils/user/getAutoAssignedRoles.ts
  src/utils/user/updateUserGroups.ts
Labels: enhancement

#447 AB#36418 aggregation with choices by url
  src/utils/form/getDisplayText.ts
Labels: bug

#449 Feat 1.3.0/ab#42909 distribution lists in app
  migrations/1669104825942-generate-templates.ts
  migrations/1669105270797-generate-distribution-lists.ts
  src/models/application.model.ts
  src/models/distributionList.model.ts
  src/models/index.ts
  src/schema/inputs/distributionList.input.ts
  src/schema/mutation/addDistributionList.mutation.ts
  src/schema/mutation/deleteDistributionList.mutation.ts
  src/schema/mutation/editDistributionList.mutation.ts
  src/schema/mutation/index.ts
  src/schema/types/application.type.ts
  src/schema/types/distributionList.type.ts
  src/schema/types/index.ts
  src/security/defineUserAbility.ts
  src/security/extendAbilityForApplication.ts
  src/utils/validators/validateEmail.ts
Labels: enhancement

#450 OORT-518 - store migrations file status outside docker
  docker-compose.dist.yml
  docker-compose.yml
  package.json
Labels: bug, enhancement
