Repository ReliefApplications/ems-backend, pull requests merged in 2022-09, with the labels that each got.

#391 fix-1.3.0/OORT-436_add_more_validation_to_related_name
  src/i18n/en.json
  src/i18n/test.json
  src/schema/mutation/addForm.mutation.ts
  src/schema/mutation/addReferenceData.mutation.ts
  src/schema/mutation/editForm.mutation.ts
  src/schema/mutation/editReferenceData.mutation.ts
  src/utils/form/extractFields.ts
  src/utils/validators/validateApi.ts
  src/utils/validators/validateName.ts
Labels: bug, enhancement

#396 refactor-1.3.0/AB#40630_layout-pagination
  src/schema/types/form.type.ts
  src/schema/types/layout.type.ts
  src/schema/types/resource.type.ts
Labels: refactor

#398 refactor-1.3.0/AB#40915_aggregation-pagination
  src/schema/mutation/editAggregation.mutation.ts
  src/schema/types/aggregation.type.ts
  src/schema/types/resource.type.ts
Labels: enhancement, refactor

#407 Feat 1.4.0/ab#34852 aggregations in summary cards
  src/schema/query/recordsAggregation.query.ts
  src/utils/aggregation/buildPipeline.ts
Labels: enhancement

#410 feat-1.30/OORT-439_sorting-applications_FO
  src/schema/types/user.type.ts
Labels: enhancement

#397 Refactor-1.4.0/AB#39903 placeholders convention
  .gitignore
  migrations/1664441608216-placeholders.ts
  src/const/email.ts
  src/const/placeholders.ts
  src/routes/email/index.ts
  src/schema/mutation/editReferenceData.mutation.ts
  src/server/apollo/dataSources.ts
  src/server/pullJobScheduler.ts
  src/setup/migrateAggregations.ts
  src/setup/migrateCharts.ts
  src/setup/migrateGraphQLTypeNames.ts
  src/setup/migrateLayouts.ts
  src/setup/migrateStandaloneForms.ts
  src/utils/email/gridEmailBuilder.ts
  src/utils/filter/getDateForMongo.ts
  src/utils/filter/getFilter.ts
  src/utils/filter/getTimeForMongo.ts
  src/utils/form/transformRecord.ts
  src/utils/schema/resolvers/Query/getFilter.ts
Labels: enhancement, refactor

#417 fix: special characters removed from the destination file name. fix d…
  src/routes/download/index.ts
  src/utils/files/format.helper.ts
Labels: enhancement
