Repository ReliefApplications/ems-backend, pull requests merged in 2023-10, with the labels that each got.

#748 Fix/ab#63797 fix matrix in grid and summary card
  src/utils/form/extractFields.ts
Labels: bug

#766 fix/AB#76616_ABC-api-configuration-edition-issues-backend
  src/schema/mutation/editApiConfiguration.mutation.ts
Labels: bug

#769 OORT-feat/HIT-106-Add-channel-notifications-for-FO-roles
  src/schema/mutation/addRole.mutation.ts
Labels: enhancement

#774 fix/AB#73344_number_filter_not_considering_string_numbers
  src/utils/filter/getFilter.ts
  src/utils/schema/resolvers/Query/getFilter.ts
Labels: bug

#779 HIT-fix/HIT-112_simplyfy-staff-record-unicity
  src/schema/types/form.type.ts
  src/utils/alimentaide/onStructureAdded.ts
Labels: bug, enhancement

#760 Oort feat/im 91 add length calculation to calculated fields
  src/const/calculatedFields.ts
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
  src/utils/aggregation/expressionFromString.ts
Labels: enhancement

#771 Hit feat/HIT-110 email translations
  config/default.js
  package-lock.json
  package.json
  src/assets/emails/app-invitation/html.pug
  src/assets/emails/app-invitation/subject.pug
  src/assets/emails/create-account-to-app/html.pug
  src/assets/emails/create-account-to-app/subject.pug
  src/assets/emails/create-account/html.pug
  src/assets/emails/create-account/subject.pug
  src/assets/emails/i18n/en.json
  src/assets/emails/i18n/fr.json
  src/assets/emails/style.css
  src/utils/email/sendEmail.ts
Labels: enhancement

#763 Feat/ab#69019 allow user with read permission duplicate applications and page
  src/schema/mutation/duplicateApplication.mutation.ts
  src/schema/mutation/duplicatePage.mutation.ts
Labels: enhancement

#778 Feat/ab#77439 unavailable graphql playground when accessing graphql endpoint
  src/server/index.ts
Labels: bug, enhancement

#783 Added a slash to the end of the url in the email button
  src/utils/user/sendUserInvitation.ts
Labels: bug

#786 AB#77897 - incorrect list of permissions in backoffice
  src/schema/query/permissions.query.ts
Labels: bug

#785 feat/AB#77814_Record's-history-download-is-not-working-for-non-admin-users
  src/routes/download/index.ts
  src/schema/query/recordHistory.query.ts
Labels: bug, enhancement

#782 AB#77434 - Improve duplication of application
  __tests__/services/page.service.test.ts
  src/schema/mutation/addCustomNotification.mutation.ts
  src/schema/mutation/duplicateApplication.mutation.ts
  src/schema/mutation/editCustomNotification.mutation.ts
  src/services/page.service.ts
Labels: bug, enhancement

#790 fix/HIT-131-add-check-if-date-exist-for-calculated-fields
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
Labels: bug

#795 fix/AB#78167-error-duplicatindapp-with-existing-name
  src/i18n/en.json
  src/i18n/test.json
  src/schema/mutation/duplicateApplication.mutation.ts
Labels: bug

#793 fix/AB#68744-GraphQL-endpoint-in-API-configuration
  src/schema/mutation/editApiConfiguration.mutation.ts
Labels: bug
