Repository ReliefApplications/ems-backend, pull requests merged in 2023-11, with the labels that each got.

#794 feat/HIT-134_Change-NextStepOnSave-Logic
  src/models/step.model.ts
  src/models/workflow.model.ts
  src/schema/mutation/editStep.mutation.ts
  src/schema/types/step.type.ts
  src/schema/types/workflow.type.ts
  src/services/page.service.ts
Labels: enhancement

#798 feat/AB#78304-sort-on-multiple-fields-in-aggregation
  src/utils/aggregation/buildPipeline.ts
Labels: enhancement

#789 AB#74821 authorization code possibility for api config
  src/const/enumTypes.ts
  src/i18n/en.json
  src/i18n/test.json
  src/routes/download/index.ts
  src/routes/gis/index.ts
  src/routes/proxy/index.ts
  src/schema/mutation/editApiConfiguration.mutation.ts
  src/schema/mutation/fetchGroups.mutation.ts
  src/server/apollo/context.ts
  src/server/apollo/dataSources.ts
  src/server/pullJobScheduler.ts
  src/utils/history/recordHistory.ts
  src/utils/proxy/authManagement.ts
  src/utils/user/fetchGroups.ts
Labels: enhancement

#802 AB#74319 : Save draft record
  src/models/draftRecord.model.ts
  src/models/index.ts
  src/schema/mutation/addDraftRecord.mutation.ts
  src/schema/mutation/deleteDraftRecord.mutation.ts
  src/schema/mutation/editDraftRecord.mutation.ts
  src/schema/mutation/index.ts
  src/schema/query/draftRecords.query.ts
  src/schema/query/index.ts
  src/schema/types/draftRecord.type.ts
  src/schema/types/index.ts
Labels: enhancement

#817 AB#78826: Some pages can't open with new gridster changes
  src/schema/types/dashboard.type.ts
Labels: bug

#815 fix/AB#57979_read_only_field_is_working_when_updating_record
  src/schema/mutation/editRecord.mutation.ts
  src/security/extendAbilityForRecords.ts
Labels: bug

#812 feat/HIT-161_Option-to-omit-question-from-fields
  src/utils/form/extractFields.ts
Labels: enhancement

#824 feat/#AB#78673_Add-more-options-to-dashboard
  src/models/dashboard.model.ts
  src/schema/mutation/editDashboard.mutation.ts
  src/schema/types/dashboard.type.ts
Labels: enhancement

#826 Ab#78944 fix ping request and avoid decrypting twice
  src/routes/proxy/index.ts
  src/server/apollo/dataSources.ts
  src/utils/proxy/authManagement.ts
Labels: bug, enhancement

#825 AB#78956_add_cache_for_auth_code_and_add_body
  src/routes/proxy/index.ts
Labels: enhancement, help wanted

#835 fix/AB#79481_roles_dont_appear_in_users_application
  src/schema/types/user.type.ts
Labels: bug

#836 fix/AB#79458_size-operation-on-nullish-values
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
Labels: bug

#842 AB#79869_incorrect_cursor_when_no_sorting
  src/schema/query/apiConfigurations.query.ts
  src/schema/query/pullJobs.query.ts
Labels: bug

#834 AB#79260: dashboard filter new options
  migrations/1700653450166-set-contextualfilter-to-dashboard-level.ts
  src/models/dashboard.model.ts
  src/schema/inputs/dashboard-filter.input.ts
  src/schema/mutation/duplicateApplication.mutation.ts
  src/schema/mutation/editApplication.mutation.ts
  src/schema/mutation/editDashboard.mutation.ts
  src/schema/types/application.type.ts
  src/schema/types/dashboard.type.ts
Labels: enhancement
