Repository ReliefApplications/ems-backend, pull requests merged in 2023-09, with the labels that each got.

#722 AB#74215 - fix: layers using lat & long could break popup
  src/routes/gis/index.ts
Labels: bug

#723 refactor/AB#74219_order-ref-data-select
  src/schema/query/referenceDatas.query.ts
  src/server/apollo/context.ts
  src/utils/date/getICULocale.ts
Labels: enhancement

#724 OORT-feat/IM-28-replace-grid-actions-menu-if-single-action
  src/schema/inputs/layout.input.ts
Labels: enhancement

#729 fixed dashboard name when context
  src/schema/mutation/addDashboardWithContext.mutation.ts
Labels: enhancement

#720 refactor/AB#61061_update-apollo
  package-lock.json
  package.json
  src/const/defaultRecordFields.ts
  src/index.ts
  src/routes/upload/index.ts
  src/schema/mutation/addRecord.mutation.ts
  src/schema/mutation/deletePullJob.mutation.ts
  src/schema/mutation/index.ts
  src/schema/mutation/publish.mutation.ts
  src/schema/mutation/seeNotifications.mutation.ts
  src/schema/mutation/uploadApplicationStyle.ts
  src/schema/mutation/uploadFile.mutation.ts
  src/schema/query/channels.query.ts
  src/schema/query/groups.query.ts
  src/schema/query/permissions.query.ts
  src/schema/query/recordHistory.query.ts
  src/schema/query/roles.query.ts
  src/schema/query/rolesFromApplications.query.ts
  src/schema/query/steps.query.ts
  src/schema/query/user.query.ts
  src/schema/query/users.query.ts
  src/schema/query/workflows.query.ts
  src/schema/types/access.type.ts
  src/schema/types/application.type.ts
  src/schema/types/channel.type.ts
  src/schema/types/form.type.ts
  src/schema/types/group.type.ts
  src/schema/types/historyVersion.type.ts
  src/schema/types/notification.type.ts
  src/schema/types/page.type.ts
  src/schema/types/positionAttribute.type.ts
  src/schema/types/positionAttributeCategory.type.ts
  src/schema/types/pullJob.type.ts
  src/schema/types/record.type.ts
  src/schema/types/referenceData.type.ts
  src/schema/types/resource.type.ts
  src/schema/types/role.type.ts
  src/schema/types/step.type.ts
  src/schema/types/subscription.type.ts
  src/schema/types/user.type.ts
  src/schema/types/version.type.ts
  src/server/apollo/context.ts
  src/server/apollo/dataSources.ts
  src/server/apollo/index.ts
  src/server/apollo/onConnect.ts
  src/server/index.ts
  src/server/middlewares/auth.ts
  src/utils/files/downloadFile.ts
  src/utils/files/uploadFile.ts
  src/utils/form/getDisplayText.ts
  src/utils/history/recordHistory.ts
  src/utils/schema/buildSchema.ts
  src/utils/schema/introspection/getFieldType.ts
  src/utils/schema/introspection/getSchema.ts
  src/utils/schema/resolvers/Entity/index.ts
  src/utils/schema/resolvers/Meta/index.ts
  src/utils/schema/resolvers/Query/single.ts
Labels: enhancement, refactor

#745 OORT-fix/IM-14_invisible-fields-get-back-to-visible
  src/schema/mutation/editForm.mutation.ts
  src/utils/form/preserveChildProperties.ts
  src/utils/form/replaceField.ts
Labels: bug

#750 fix: display of linked items on grid not showing when has more then 1…
  src/utils/schema/resolvers/Query/all.ts
Labels: bug

#753 Oort feat/im 70 add ability to duplicate resource
  src/schema/mutation/duplicateResource.mutation.ts
  src/schema/mutation/index.ts
Labels: enhancement
