Repository ReliefApplications/ems-backend, pull requests merged in 2023-12, with the labels that each got.

#844 feat/AB#80380_Navigating-from-a-dashboard-with-edited-configuration-to-one-without-a-saved-one-may-create-conflicts
  src/schema/types/dashboard.type.ts
Labels: bug, enhancement, in code review, refactor

#852 Bugfix/ab#80663 abc incorrect api configuration and reference data view
  src/schema/query/apiConfigurations.query.ts
  src/schema/query/applications.query.ts
Labels: enhancement

#854 feat/AB#80866_ABC-use-collation-for-all-queries-that-require-sorting-…
  src/schema/query/applications.query.ts
  src/schema/query/forms.query.ts
  src/schema/query/resources.query.ts
Labels: enhancement

#851 Ab#67193 upload record from excel
  src/utils/files/loadRow.ts
Labels: bug

#858 fix/AB#80830_fields_not_working_in_export
  src/utils/files/exportBatch.ts
  src/utils/files/getRowsFromMeta.ts
Labels: bug

#811 Indexing and aggregation pipeline optimisation
  src/models/form.model.ts
  src/models/record.model.ts
  src/models/resource.model.ts
  src/schema/mutation/editResource.mutation.ts
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
  src/utils/schema/resolvers/Query/all.ts
  src/utils/schema/resolvers/Query/getFilter.ts
  src/utils/schema/resolvers/Query/getSearchFilter.ts
Labels: enhancement, in code review, refactor

#857 AB#80959_fix_timezone_for_export
  src/utils/files/exportBatch.ts
  src/utils/files/getRowsFromMeta.ts
  src/utils/history/recordHistory.ts
  src/utils/schema/resolvers/Query/getFilter.ts
Labels: bug

#861 refactor: reference data pipeline stage
  src/models/referenceData.model.ts
  src/schema/query/recordsAggregation.query.ts
  src/utils/aggregation/buildReferenceDataAggregation.ts
  src/utils/schema/resolvers/Query/all.ts
Labels: bug, refactor

#843 feat/AB#79593 Automatically assign Ownership on Information records from EIOS based on the article's board name
  src/server/EIOSOwnernshipMapping.ts
  src/server/pullJobScheduler.ts
Labels: enhancement

#875 Ab#81454 add ref data support for layers
  src/routes/gis/index.ts
  src/server/index.ts
Labels: enhancement

#877 fix/AB#81524_aggregation_on_refData_not_working
  src/schema/query/referenceDataAggregation.query.ts
Labels: bug

#876 AB#79593 Assign ownership in EIOS pulljob : version 2
  src/server/pullJobScheduler.ts
Labels: bug, enhancement

#884 Feat/ab#81625 add search on top of layers selection
  src/schema/query/layers.query.ts
Labels: enhancement

#887 fix/AB#79593_EIOS-pulljob-assign-ownership-async-fix
  src/server/EIOSOwnernshipMapping.ts
  src/server/pullJobScheduler.ts
Labels: enhancement

#886 feat/AB#81670_ABC-button-to-preview-aggregation-data
  src/schema/query/recordsAggregation.query.ts
  src/schema/query/referenceDataAggregation.query.ts
Labels: enhancement

#885 fix/AB#81442_filter-on-refData-aggregations
  src/schema/query/referenceDataAggregation.query.ts
  src/utils/schema/resolvers/Query/getFilter.ts
Labels: enhancement

#595 feat/AB#63539_improvments-on-contextualized-dashboards
  src/schema/mutation/addDashboardWithContext.mutation.ts
  src/schema/types/dashboard.type.ts
  src/utils/context/getContextData.ts
Labels: enhancement, keep, refactor

#893 AB#81995_add_unwind_possibility_for_reference_data_aggregation
  src/schema/query/referenceDataAggregation.query.ts
Labels: enhancement

#905 fix: aggregation on null question using choices from refData
  src/utils/aggregation/buildReferenceDataAggregation.ts
Labels: bug
