Repository ReliefApplications/ems-backend, pull requests merged in 2023-01, with the labels that each got.

#490 refactor/AB#51548_hide-grid-add-button
  src/schema/types/resource.type.ts
  src/security/extendAbilityForRecords.ts
Labels: enhancement

#496 fix: sorting on multi select field could break records aggregation
  src/utils/schema/resolvers/Query/getSortAggregation.ts
Labels: bug

#497 AB#50996 Fix 401 errors due to validation with choicesByUrl
  src/schema/mutation/editRecord.mutation.ts
  src/schema/mutation/editRecords.mutation.ts
  src/utils/form/checkRecordValidation.ts
Labels: bug

#429 Feat 1.3.0/oort 471 create meaningful errors when env variables are missing
  __tests__/utils/server/checkConfig.test.ts
  src/index.ts
  src/utils/server/checkConfig.util.ts
Labels: enhancement

#485 Fix 1.3.x/AB#26880 aggregation with grids
  src/schema/query/recordsAggregation.query.ts
  src/security/extendAbilityForRecords.ts
  src/utils/aggregation/setDisplayText.ts
Labels: bug, enhancement

#504 refactor/AB#51900_use_casl_in_front_to_manage_permissions
  src/schema/types/application.type.ts
  src/utils/user/getAutoAssignedRoles.ts
Labels: enhancement

#507 AB#29960 fix issue with filters on see and update access
  src/schema/mutation/editResource.mutation.ts
Labels: bug
