Repository ReliefApplications/ems-backend, pull requests merged in 2023-05, with the labels that each got.

#590 feat/add-substr-calculation
  src/const/calculatedFields.ts
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
  src/utils/aggregation/expressionFromString.ts
Labels: enhancement

#446 OORT-460 Loop through all dashboards for aggregation migration
  migrations/1663832564479-generate-aggregations.ts
Labels: bug

#597 fix/optimize-calcFields-pipeline
  src/i18n/en.json
  src/i18n/test.json
  src/schema/mutation/editResource.mutation.ts
  src/utils/aggregation/buildCalculatedFieldPipeline.ts
  src/utils/schema/resolvers/Query/all.ts
Labels: bug, enhancement

#604 fix/error-updating-resurce-permissions
  src/schema/mutation/editResource.mutation.ts
  src/security/extendAbilityForRecords.ts
  src/server/database.ts
Labels: bug
