Repository ReliefApplications/ems-backend, pull requests merged in 2024-01, with the labels that each got.

#810 AB#71959 - replace rabbitmq with redis
  package-lock.json
  package.json
  src/index.ts
  src/schema/mutation/addApplication.mutation.ts
  src/schema/mutation/addSubscription.mutation.ts
  src/schema/mutation/deleteSubscription.mutation.ts
  src/schema/mutation/editSubscription.mutation.ts
  src/schema/subscription/applicationEdited.subscription.ts
  src/schema/subscription/applicationUnlocked.subscription.ts
  src/schema/subscription/notification.subscription.ts
  src/schema/subscription/recordAdded.subscription.ts
  src/schema/types/channel.type.ts
  src/server/pubsub.ts
  src/server/pubsubSafe.ts
  src/server/subscriberSafe.ts
Labels: enhancement, in code review, refactor, dependencies

#914 fix/AB#82914-duplication-of-app-sometimes-fail
  src/schema/mutation/duplicateApplication.mutation.ts
Labels: bug

#908 AB#82404_filter_was_overwritten_by_changes
  src/schema/mutation/editDashboard.mutation.ts
Labels: bug

#913 refactor/AB#82670_serverside-introspection
  src/schema/query/index.ts
  src/schema/query/types.query.ts
  src/server/apollo/queries/introspection.query.ts
  src/server/index.ts
Labels: refactor

#924 feat/AB#83116-avoid-duplication-of-redis-client
  src/routes/proxy/index.ts
  src/server/redis.ts
  src/utils/gis/getCountryPolygons.ts
Labels: enhancement, refactor

#930 fix/AB#82914-duplication-of-app-sometimes-fail
  src/schema/mutation/duplicateApplication.mutation.ts
Labels: bug

#935 feat/AB#83237_use_regex_when_using_reference_data_and_dashboard_filter
  src/schema/query/referenceDataAggregation.query.ts
Labels: enhancement

#936 fix/AB#83339-'or'-logic-with-no-filter-value-prevents-data-loading
  src/schema/query/referenceDataAggregation.query.ts
  src/utils/referenceData/referenceDataFilter.util.ts
Labels: bug

#932 feat: add pagination info to reference data
  src/i18n/en.json
  src/models/referenceData.model.ts
  src/routes/gis/index.ts
  src/schema/mutation/editReferenceData.mutation.ts
  src/schema/types/referenceData.type.ts
  src/server/pullJobScheduler.ts
Labels: enhancement

#947 Ab#83728 add graphql variables support for aggregations inside text widget
  src/schema/query/referenceDataAggregation.query.ts
  src/server/apollo/dataSources.ts
Labels: enhancement

#948 feat/AB#83726-be-able-to-pass-graphql-variables-in-map-layers
  src/models/layer.model.ts
  src/routes/gis/index.ts
  src/routes/proxy/index.ts
  src/schema/inputs/layer.input.ts
  src/schema/types/layer.type.ts
  src/server/apollo/dataSources.ts
  src/utils/gis/getCountryPolygons.ts
  src/utils/proxy/authManagement.ts
Labels: enhancement

#907 AB#82193 : AddFields for aggregation with referenceData
  src/routes/gis/index.ts
  src/schema/query/referenceDataAggregation.query.ts
  src/server/apollo/dataSources.ts
Labels: enhancement

#956 feat/AB#83917_refactor_layers_query_in_map_edition
  src/schema/query/layers.query.ts
Labels: enhancement, refactor

#964 AB#84797 - Change permissions of layers
  src/schema/query/layer.query.ts
  src/schema/query/layers.query.ts
Labels: enhancement

#946 Ab#83681 support for context in front office without templates
  src/i18n/en.json
  src/i18n/test.json
  src/schema/mutation/addDashboardWithContext.mutation.ts
  src/schema/mutation/index.ts
  src/schema/query/dashboard.query.ts
  src/schema/types/dashboard.type.ts
  src/utils/context/getContextData.ts
  src/utils/context/getNewDashboardName.ts
Labels: bug, enhancement
